version: "3.8"

services:
    website:
        build: 
            context: . # build using the DockerFile in the same directory
            args:
                - myUserID # obtain the argument value from .env and provide it to the docker build time
        image: linux4hope/website-v2:latest # tage the time with the specified name and tag
        container_name: linux4hope-website-v2
        volumes:
            - ./:/home/dev/workspace # bind mount from our current folder to the workspace folder in the container
        ports:
            - "8000:8000" # publish port 8000 on the container and map it to the host